### ISSUE TITLE
Color of icon

### ISSUE THREAD

**Issue by Zykino** [lesspass/cozy#1]
All the standard applications in cozy cloud have black icons.
Could you change the icon of yours to be more uniform in my list of apps?
(Just revert the color from white to black should be nice.)

**Comment by guillaumevincent** [comment]
Sure, I will change the color to black

**Comment by guillaumevincent** [comment]
@Zykino Is it better with this icon?

**Comment by Zykino** [comment]
Look like this now so Yes I think it's better :) (changed in the inspector)

![lesspasscozy](https://cloud.githubusercontent.com/assets/3809938/18104892/95e613a8-6efd-11e6-83c9-5c723fe83066.png)

**Comment by guillaumevincent** [comment]
Great thanks !
